### ISSUE TITLE
Issue in when i am registering the user i am getting unknown integral data type for ids : java.lang.string error

### ISSUE THREAD

**Issue by SmrutiJena** [ikismail/ShoppingCart#43]
Hi I am using oracle DB and when i am deploying application and trying to register user into it i am facing below error .
Tried multiple option to generate the @id but still getting the same error.
Could you please help me in that. 

rg.hibernate.id.IdentifierGenerationException: Unknown integral data type for ids : java.lang.String] with root cause
	org.hibernate.id.IdentifierGenerationException: Unknown integral data type for ids : java.lang.String
		at org.hibernate.id.IdentifierGeneratorHelper.getIntegralDataTypeHolder(IdentifierGeneratorHelper.java:182)
		at org.hibernate.id.SequenceGenerator.buildHolder(SequenceGenerator.java:150)
		at org.hibernate.id.SequenceGenerator.generateHolder(SequenceGenerator.java:126)
		at org.hibernate.id.SequenceGenerator.generate(SequenceGenerator.java:116)
		at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:120)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:204)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:189)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:114)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
		at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:615)
		at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:608)
		at org.hibernate.engine.spi.CascadingAction$5.cascade(CascadingAction.java:258)
		at org.hibernate.engine.internal.Cascade.cascadeToOne(Cascade.java:380)
		at org.hibernate.engine.internal.Cascade.cascadeAssociation(Cascade.java:323)
		at org.hibernate.engine.internal.Cascade.cascadeProperty(Cascade.java:208)
		at org.hibernate.engine.internal.Cascade.cascade(Cascade.java:165)
		at org.hibernate.event.internal.AbstractSaveEventListener.cascadeBeforeSave(AbstractSaveEventListener.java:437)
		at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:266)
		at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:195)
		at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:138)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:204)
		at org.hibernate.event.internal.DefaultSaveEventListener.saveWithGeneratedOrRequestedId(DefaultSaveEventListener.java:55)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:189)
		at org.hibernate.event.internal.DefaultSaveEventListener.performSaveOrUpdate(DefaultSaveEventListener.java:49)
		at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:90)
		at org.hibernate.internal.SessionImpl.fireSave(SessionImpl.java:642)
		at org.hibernate.internal.SessionImpl.save(SessionImpl.java:635)
		at org.hibernate.internal.SessionImpl.save(SessionImpl.java:631)
		at com.dao.CustomerDaoImpl.addCustomer(CustomerDaoImpl.java:47)
		at com.service.CustomerServiceImpl.addCustomer(CustomerServiceImpl.java:24)

**Comment by JoeHermann21** [comment]
change the IDs type for Integer instead of String
